mess_portal/blog/urls.py
from django.conf.urls import url

from blog import views
app_name ='blog'
urlpatterns =[
	url (r'^$',views.index_api_get,name='index'),
	url (r'^add_question',views.add_question,name='question'),
	url(r'^question/(?P<question_id>[0-9]+)/$',views.api_detail,name='detail'),
	url(r'^question/(?P<question_id>[0-9]+)/handling/$',views.handling,name='handling'),
]

mess_portal/mess_menu/urls.py
from django.conf.urls import url

from . import views
app_name = 'mess_menu'
urlpatterns = [
		url(r'^todaymenu_api', views.todaymenu_api, name='todaymenu_api'),
		url(r'^menu_api/(?P<day_id>[0-9]+)/$', views.menu_api, name='menu_api'),
		url(r'^day_list_api', views.day_list_api, name='day_list_api'),
        url(r'^today', views.today, name='today'),
        url(r'^$', views.index, name='index'),
	    url (r'opt_out/handle',views.decrement,name='handle'),
		url (r'opt_out',views.opt_out,name='opt_out' ),
        url(r'^(?P<day_id>[0-9]+)/$', views.detail, name='detail'),
        ]

mess_portal/mess_portal/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^$',include('signup.urls1')),
    url(r'^signin/',include('signin.urls')),
    url(r'^signup/',include('signup.urls')),
    url(r'^blog/',include('blog.urls')),
    url(r'^mess_menu/', include('mess_menu.urls')),
    url(r'^feedback/',include('feedback.urls')),
    url(r'^admin/', admin.site.urls),
]

mess_portal/signin/urls.py
from django.conf.urls import url
from . import views
app_name = 'signin'

urlpatterns = [
	url(r'^signin_api$',views.signin_api,name='signin_api'),
	url(r'^handling_api$',views.handling_api,name='handling_api'),
	#url(r'^$',views.signin,name='signin'),
	url(r'signout',views.signout,name='signout'),
	#url(r'^handling',views.handling,name='handling'),
]

mess_portal/mess_menu/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.db.models import Count
from django.contrib.auth.models import User
import datetime






class Day(models.Model):
    day_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.day_name


       
class Food(models.Model):
    food_time = models.CharField(max_length=100)
    
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.food_time 

class ToOptOut(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	optedOut1 = models.BooleanField(default=False)
	optedOut2 = models.BooleanField(default=False)
	optedOut3 = models.BooleanField(default=False)
	date        = models.DateField()    
	



	
	
	




	

mess_portal/mess_menu/views.py
from rest_framework.decorators import api_view
from rest_framework import serializers, status
from rest_framework.response import Response

from django.shortcuts import render,  get_object_or_404

from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from .models import Day, Food,ToOptOut
from django.core.urlresolvers import reverse
import datetime

def index(request):
    day_list = Day.objects.all()
    context = {'day_list': day_list}
    return render(request, 'mess_menu/index.html', context)

def detail(request, day_id):
    day = get_object_or_404(Day,pk = day_id)
    return render(request,'mess_menu/detail.html',{'day':day})

def today(request):
    foodcount1 = User.objects.count() - ToOptOut.objects.filter(date=datetime.date.today(),optedOut1=True).count()
    foodcount2 = User.objects.count() - ToOptOut.objects.filter(date=datetime.date.today(),optedOut2=True).count()
    foodcount3 = User.objects.count() - ToOptOut.objects.filter(date=datetime.date.today(),optedOut3=True).count()
    day_list = Day.objects.all()
    date = timezone.now()
    today_name = date.today().strftime("%A")
    count = []
    count.append(foodcount1)
    count.append(foodcount2)
    count.append(foodcount3)			
    context = {
        'count':count,
        'day_list': day_list,
        'today_name': today_name,
    }
    return render(request, 'mess_menu/today.html', context)


def opt_out (request):
	if request.user.is_authenticated():
		username  = request.user
		user = User.objects.get(username= username)
		optOut = user.tooptout_set.get(date=datetime.date.today())
		context = {'opted_out_1':opOut.optedOut1,
			'opted_out_2':opOut.optedOut2,
			'opted_out_3':opOut.optedOut3}
		return render (request,'mess_menu/opt_out.html',context)
	else:
		return HttpResponseRedirect(reverse('signin:signin')) 


def decrement (request):
	username  = request.user
	user = User.objects.get(username= username)
	optOut = user.tooptout_set.get(date=datetime.date.today())
	if 'breakfast'  in request.POST:
		optOut.optOut1 = True
	if 'lunch'  in request.POST:
		optOut.optOut2 = True
	if 'dinner'  in request.POST:
		optOut.optOut3 = True
	optOut.save()
	return HttpResponseRedirect (reverse('mess_menu:today'))
    
	

@api_view(['GET'])
def day_list_api(request):
    
    day_model_list = Day.objects.all()
    
    day_python_list = []
    for day in day_model_list:
        python_day = Typeclass(day=day.day_name)
        day_python_list.append(python_day)

    serializer_list = Serializer(day_python_list, many=True)
    
    return Response(status=status.HTTP_200_OK, data=serializer_list.data)



class Typeclass():
    def __init__(self, day):
        self.day = day    


class Serializer(serializers.Serializer):
     day = serializers.CharField()







    
class menutypeclass():
    def __init__(self, food):
        self.food = food 

class daytypeclass():
    def __init__(self, day, menu):
        self.day = day
        self.menu = menu  

class foodserializer(serializers.Serializer):
    food = serializers.CharField()

class daymenu_serializer(serializers.Serializer):
    day = serializers.CharField()
    menu = foodserializer(many= True)  


@api_view(['GET'])   
def menu_api(request, day_id):
    
    day = Day.objects.get(id = day_id)
    menu = day.food_set.all()
    menu_list = []
    
    for x in menu:
        x_py = menutypeclass(food = x.food_time)
        menu_list.append(x_py)

    py_object = daytypeclass(day = day.day_name, menu = menu_list)
    py_ob_ser = daymenu_serializer(py_object)  

    return Response(status=status.HTTP_200_OK, data= py_ob_ser.data)


@api_view(['GET'])   
def todaymenu_api(request):

    date = timezone.now()
    today_name = date.today().strftime("%A")
    print(today_name)
    i=1
    
    
    for day in Day.objects.all():
        if today_name == day.day_name:
            print(day.day_name)
            day_id = i
        i =i+1     


    day = Day.objects.get(id = day_id)
    menu = day.food_set.all()
    menu_list = []
    for x in menu:
        x_py = menutypeclass(food = x.food_time)
        menu_list.append(x_py)

    py_object = daytypeclass(day = day.day_name, menu = menu_list)
    py_ob_ser = daymenu_serializer(py_object)  

    return Response(status=status.HTTP_200_OK, data= py_ob_ser.data)









    
















    
    
    

    

mess_portal/mess_menu/templates/mess_menu/detail.html
<h1>{{ day.day_name }}'s Menu</h1>

<ul>
{% for food in day.food_set.all %}
    <li>{{ food.food_time }}</li><br>
{% endfor %}
</ul>
<br><br><br><br><br><br><br>

<a href ="{% url 'signin:signout' %}"> <b> signout</b></a>

mess_portal/mess_menu/templates/mess_menu/index.html
<ul>
    {% for day in day_list %}
        <li><a href="/mess_menu/{{ day.id }}/">{{ day.day_name }}</a></li><br>
    {% endfor %}
</ul>
<br><br><br><br><br><br><br>

<a href ="{% url 'signin:signout' %}"> <b> signout</b></a>

mess_portal/mess_menu/templates/mess_menu/opt_out.html
<h2>Opt out for any of the following for tomorrow :</h2>

<form action= "{% url 'mess_menu:handle' %}" method= "post">
{% csrf_token %}
{% if not opted_out_1 %}
	<input type="radio" name="breakfast" value='1' >breakfast<br>
{% endif %}

{% if not opted_out_2 %}
	<input type="radio" name="lunch" value='2' >lunch<br>
{% endif %}

{% if not opted_out_3 %}
	<input type="radio" name="dinner" value='3' >dinner<br>
{% endif %}

{% if  opted_out_1 and opted_out_2 and opted_out_3 %}
	<b>You opted out for every meal for tomorrow</b><br>
{% endif %}

<input type="submit" value="opt_out">
</form>
<br><br><br><br><br><br><br>

<a href ="{% url 'signin:signout' %}"> <b> signout</b></a>

mess_portal/mess_menu/templates/mess_menu/today.html
<a href="{% url 'blog:index' %}" ><h2> mess blog</h2> </a> <a href="{% url 'feedback_index' %}">
<h2> feedback </h2>
</a>
<ul>
{% for day in day_list %}
	{% if today_name == day.day_name %}
		<li><a href = "/mess_menu/{{ day.id }}/"><b>Click here for Today's Menu</b></a></li><br>
	{% endif %}
{% endfor %}

<li><a href = "/mess_menu/"><b>This Week's Menu</b></a></li><br>

</ul>


<h3>Food Count for Tomorrow :</h3>
<ul>
<li>Breakfast : {{ count.0 }} </li>
<li>lunch     : {{ count.1 }} </li>
<li>dinner    : {{ count.2 }} </li>
</ul>
<br><br><br>

<a href="{% url 'mess_menu:opt_out' %}"> <b> opt_out for tomorrow's mess</b></a>

<br><br><br><br><br><br><br>

<a href ="{% url 'signin:signout' %}"> <b> signout</b></a>